# Generated by Django 5.0.6 on 2024-06-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Employeement_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_reference', models.CharField(max_length=100)),
                ('Period', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Data_value', models.IntegerField(blank=True, null=True)),
                ('Suppressed', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(max_length=100)),
                ('Units', models.CharField(max_length=100)),
                ('Magnitude', models.IntegerField()),
                ('Subject', models.CharField(max_length=100)),
                ('Group', models.CharField(max_length=100)),
                ('Series_title_1', models.CharField(max_length=100)),
                ('Series_title_2', models.CharField(max_length=100)),
                ('Series_title_3', models.CharField(max_length=100)),
            ],
        ),
    ]
